SELECT
  RECURSOSHUMANOS.RHCarreras.idCarrera,
  RECURSOSHUMANOS.RHCarreras.NombreCarrera,
  RECURSOSHUMANOS.RHCarreras.Descripcion,
  RECURSOSHUMANOS.RHCarreras.idGrupoCarrera,
  RECURSOSHUMANOS.RHCarreras.ELIMINADO,
  RECURSOSHUMANOS.RHCarreras.XDEFAULT,
  RECURSOSHUMANOS.RHCarreras.FECHAHORACAMBIO,
  RECURSOSHUMANOS.RHCarreras.IDUSUARIO,
  RECURSOSHUMANOS.RHCarreras.DESISTEMA,
  RECURSOSHUMANOS.RHGruposCarrera.NombreGrupoCarrera
FROM
  RECURSOSHUMANOS.RHCarreras
  JOIN RECURSOSHUMANOS.RHGruposCarrera ON RECURSOSHUMANOS.RHCarreras.idGrupoCarrera = RECURSOSHUMANOS.RHGruposCarrera.idGrupoCarrera;