SELECT
  idPUESTO,
  NombrePuesto,
  NombreLargo,
  Descripcion,
  ELIMINADO,
  CASE
    ELIMINADO
    WHEN 0 THEN 'No'
    WHEN 1 THEN 'Si'
  END AS DESELIMINADO,
  CASE
    DESISTEMA
    WHEN 0 THEN 'No'
    WHEN 1 THEN 'Si'
  END AS DESDESISTEMA,
  IDUSUARIO,
  FECHAHORACAMBIO
FROM
  RECURSOSHUMANOS.RHPuestos;