SELECT
  idZona,
  NombreZona,
  ELIMINADO,
  CASE
    ELIMINADO
    WHEN 0 THEN 'no'
    WHEN 1 THEN 'si'
  END AS DESELIMINADO,
  XDEFAULT,
  CASE
    XDEFAULT
    WHEN 0 THEN 'no'
    WHEN 1 THEN 'si'
  END AS DESXDEFAULT,
  IDUSUARIO,
  FECHAHORACAMBIO
FROM
  COMUNES.COMZonas;