SELECT
  COMUNES.COMEstados.idEstado,
  COMUNES.COMEstados.NombreEstado,
  COMUNES.COMEstados.ELIMINADO,
  COMUNES.COMEstados.XDEFAULT,
  COMUNES.COMEstados.IDUSUARIO,
  COMUNES.COMEstados.FECHAHORACAMBIO,
  COMUNES.COMPaises.IdPais,
  COMUNES.COMPaises.NombrePais
FROM
  COMUNES.COMEstados
  JOIN COMUNES.COMPaises ON COMUNES.COMEstados.idPais = COMUNES.COMPaises.IdPais;